language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$Home/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r hello-springboot-webservice *
  - mkdir -p deploy
  - mv hello-springboot-webservice.zip deploy/hello-springboot-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis Repository Settings
    secret_access_key: $AWS_SECRET_KEY  # Travis Repository Settings

    bucket: hello-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # Zip파일 접근 권한 Private
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis Repository Settings
    secret_access_key: $AWS_SECRET_KEY  # Travis Repository Settings

    bucket: hello-springboot-build # S3 버킷
    key: hello-springboot-webservice.zip # 빌드 파일을 압축해서 전달

    bundle_type: zip # 압축 확장자
    application: hello-springboot-webservice # CodeDeploy 애플리케이션
    deployment_group: hello-springboot-webservice-group # CodeDeploy 배포 그룹

    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - sprnd645@gmail.com